# Generated by Django 5.1.1 on 2024-10-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_history_notification_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeproducts',
            name='coffephoto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
