# Generated by Django 5.1.1 on 2024-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_alter_coffeproducts_coffephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffetable',
            name='profilephoto',
            field=models.CharField(blank=True, default='profilephoto', max_length=255, null=True),
        ),
    ]
